# Additional keybinds
bind = SUPER SHIFT, Return, exec, kitty --working-directory=$(pwd)
bind = SUPER, N, exec, swaync-client -t -sw
bind = SUPER, B, exec, firefox
bind = SUPER SHIFT, E, exec, thunar
