format = "$username$hostname$directory$git_branch$git_status$cmd_duration$character"

[character]
success_symbol = "[❯](bold #89b4fa)"
error_symbol = "[❯](bold #f38ba8)"

[directory]
style = "bold #cba6f7"

[username]
style_user = "bold #a6e3a1"
show_always = false

[git_branch]
symbol = "󰊢 "
style = "bold #89b4fa"

[cmd_duration]
min_time = 2000
style = "bold #f9e2af"
